### ISSUE TITLE
How do I have to configure it to have autocomplete? 

### ISSUE THREAD

**Issue by enisze** [i18nexus/next-i18n-router#57] opened 2024-02-26 23:16 UTC
I am not sure, what I am doing wrong. I would like there to be autocomplete for the strings I use like

t("common:...") This does not work for me. Do I have to do some specific configuration?

**Comment by i18nexus** [comment] 2024-02-26 23:51
I'm going to assume you're using i18next and not react-intl, but [according to these docs](https://www.i18next.com/overview/typescript) you can do something this:

```
import "i18next";
import ns1 from "locales/en/ns1.json";
import ns2 from "locales/en/ns2.json";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "ns1";
    resources: {
      ns1: typeof ns1;
      ns2: typeof ns2;
    };
  }
}
```

**Comment by enisze** [comment] 2024-03-01 10:24
Hey @i18nexus thanks for your help. This works for me, but only if I specify the default namespace and then also only for the default namespace. I was expecting e.g. ns2 to work like: t("ns2:someKey")

**Comment by i18nexus** [comment] 2024-03-01 15:28
Alternatively, if you use the same default namespace throughout your app, you could prepend "namespace:" to every key in your non-default namespaces.

**Comment by enisze** [comment] 2024-03-01 19:29
> @enisze Oh, yeah I guess using "ns2:somekey" wouldn't work. One thing you can do is pass a namespace into `useTranslation`. For example:
> 
> ```
> const t = useTranslation("ns2");
> ...
> t("someKey")
> ```
> 
> Passing the namespace to useTranslation will make `t` use it as the default namespace.

This does not work for me. It types it, but still uses the default namespace to find the translation. :/



> Alternatively, if you use the same default namespace throughout your app, you could prepend "namespace:" to every key in your non-default namespaces in the typescript interface.

What do you mean by that? Is it not possible to somehow achieve it to have somehow properly typed? 

My init looks like this: 
```
import i18nConfig from "i18nConfig";
import { createInstance, type Resource, type i18n } from "i18next";
import resourcesToBackend from "i18next-resources-to-backend";
import { initReactI18next } from "react-i18next/initReactI18next";

const namespaces = ["common", "forms", "success", "errors", "tours"];

export default async function initTranslations({
	locale,
	i18nInstance: instance,
	resources,
}: {
	locale: string;
	i18nInstance?: i18n;
	resources?: Resource;
}) {
	const i18nInstance = instance ?? createInstance();

	i18nInstance.use(initReactI18next);

	if (!resources) {
		i18nInstance.use(
			resourcesToBackend(
				(language: string, namespace: string) =>
					import(`./${language}/${namespace}.json`),
			),
		);
	}

	await i18nInstance.init({
		lng: locale,
		resources,
		fallbackLng: i18nConfig.defaultLocale,
		supportedLngs: i18nConfig.locales,
		defaultNS: namespaces[0],
		fallbackNS: namespaces[0],
		ns: namespaces,
		preload: resources ? [] : i18nConfig.locales,
	});

	return {
		i18n: i18nInstance,
		resources: i18nInstance.services.resourceStore.data,
		t: i18nInstance.t,
	};
}
```

**Comment by i18nexus** [comment] 2024-03-02 19:21
I've gone ahead and tested it out and everything seems to work for me. I've tested this with our [example project](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example).

i18next.d.ts (placed at root of the project):

```
import home from '@/locales/en/home.json';
import about from '@/locales/en/about.json';

declare module 'i18next' {
  // eslint-disable-next-line no-unused-vars
  interface CustomTypeOptions {
    defaultNS: 'home';
    resources: {
      home: typeof home;
      about: typeof about;
    };
  }
}
```

Using `t("header")` passes in both server and client components.
Using `t("about:about_header") passes in bother server and client components.
Using any key that doesn't exists does not pass.

I didn't have to change any other files in the project.

If this doesn't work for you, can you please show me your locales directory structure, your declaration of `CustomTypeOptions`, and your i18nConfig?

**Comment by enisze** [comment] 2024-03-03 01:58
I just checked the example out too and used your i18n.d.ts:
```
import home from '@/locales/en/home.json';
import about from '@/locales/en/about.json';

declare module 'i18next' {
  // eslint-disable-next-line no-unused-vars
  interface CustomTypeOptions {
    defaultNS: 'home';
    resources: {
      home: typeof home;
      about: typeof about;
    };
  }
}
```

I did try in the ExampleClientComponent. It does not work for me:
<img width="525" alt="image" src="https://github.com/i18nexus/next-i18n-router/assets/15271433/f1ecbe4e-2aff-4c2f-850c-26d80b43f028">
<img width="525" alt="image" src="https://github.com/i18nexus/next-i18n-router/assets/15271433/b11adf49-4afb-4c60-ba36-1f641ec7340d">

On the serverside on the about page it works:
<img width="525" alt="image" src="https://github.com/i18nexus/next-i18n-router/assets/15271433/478cf306-754e-4324-9c25-bd1815fa22dc">


Same behaviour which I currently have in my project.

**Comment by i18nexus** [comment] 2024-03-03 03:04
Ah, I'm sorry you're right. I can reproduce the exact same thing. One thing I have found that works is passing the namespaces into useTranslation like so:

<img width="644" alt="Screen Shot 2024-03-02 at 7 02 54 PM" src="https://github.com/i18nexus/next-i18n-router/assets/66753559/624d8495-4a87-4ed0-8379-90246a1b069f">

But obviously this isn't ideal. We'll continue taking a look at it!

**Comment by enisze** [comment] 2024-03-03 03:09
Ah alright, would use this workaround :) Thank you. Would prefer though to use the default namespace without prefix also. 
Appreciate your help :)

**Comment by i18nexus** [comment] 2024-03-03 03:11
> Would prefer though to use the default namespace without prefix also

Can you explain what you mean by this?

**Comment by i18nexus** [comment] 2024-03-03 03:43
This seems to work as well:

<img width="482" alt="Screen Shot 2024-03-02 at 7 39 31 PM" src="https://github.com/i18nexus/next-i18n-router/assets/66753559/c57b622e-f268-4811-b517-04629e2691b8">

I think the declaration is working for the 'i18next instance. So `i18n.t` has definitions, but `t` does not. I'll have to look more at why these functions respond to the declaration differently.

**Comment by enisze** [comment] 2024-03-03 19:09
> > Would prefer though to use the default namespace without prefix also
> 
> Can you explain what you mean by this?

Sure I was hoping for home (because its the default namespace):
 <img width="525" alt="image" src="https://github.com/i18nexus/next-i18n-router/assets/15271433/478cf306-754e-4324-9c25-bd1815fa22dc">
 
 To have suggestions without the prefix

**Comment by enisze** [comment] 2024-03-03 19:11
> This seems to work as well:
> 
> <img alt="Screen Shot 2024-03-02 at 7 39 31 PM" width="482" src="https://private-user-images.githubusercontent.com/66753559/309522158-c57b622e-f268-4811-b517-04629e2691b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0OTMxOTYsIm5iZiI6MTcwOTQ5Mjg5NiwicGF0aCI6Ii82Njc1MzU1OS8zMDk1MjIxNTgtYzU3YjYyMmUtZjI2OC00ODExLWI1MTctMDQ2MjllMjY5MWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE5MDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNWYxNmQ4NzZkYmI3ZGU0NjJiYjFmOWJhYzU0YTY1NjA2YzU5MzU3ZjQ5YzhmMDE5MDg5NjFlZDNlYWZkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uFi-jlE8L_hqv9RRPcA5Ml_EKKt1LnXy1iFhi51Z0F0">
> I think the declaration is working for the 'i18next instance. So `i18n.t` has definitions, but `t` does not. I'll have to look more at why these functions respond to the declaration differently.

yes it works for me like this. But as mentioned above the Default namespace is still there with a prefix, but that would be fine for me I wouldn't mind to also use the prefix always for my default NS as well.

**Comment by enisze** [comment] 2024-03-03 19:33
I just noticed the same issue for the <Trans/> component regarding the type of the i18nKey. It only includes the default NS.

**Comment by i18nexus** [comment] 2024-03-03 22:16
Yeah, including the namespace in the key for the default namespace seems to be be valid in i18next, so the TypeScript just reflects that.

**Comment by enisze** [comment] 2024-03-08 11:03
Are there any news on the <Trans/> component? The keys don't work there... Is there a workaround for these components?

**Comment by i18nexus** [comment] 2024-03-11 22:31
Using `const { i18n: { t } } = useTranslation()` seems to be the best method we can find. Does this not work for you?

**Comment by enisze** [comment] 2024-03-13 16:00
This works, 
but I am alking about the `Trans` component 

```
						<Trans
							i18nKey='about:back'
/>
```
Gives me ts errors.

**Comment by i18nexus** [comment] 2024-03-13 16:48
<img width="462" alt="Screen Shot 2024-03-13 at 9 45 19 AM" src="https://github.com/i18nexus/next-i18n-router/assets/66753559/63b33121-2aaf-4240-9a79-adc02cf85d63">

This seems to work. But the weird part is that "about" doesn't show in the autocomplete for `ns`. But TypeScript accepts "about" as a valid value regardless. Still looking into this.

**Comment by i18nexus** [comment] 2024-03-13 17:23
Here is actually a better solution to make autocomplete work:

<img width="438" alt="Screen Shot 2024-03-13 at 10 22 11 AM" src="https://github.com/i18nexus/next-i18n-router/assets/66753559/23fe986f-1ba8-4067-9d9b-b75c55b81ed2">

**Comment by i18nexus** [comment] 2024-03-13 17:28
Just to clear up where this overall issue stands:

For `useTranslation`, the react-i18next docs say to include the namespaces as an argument of `useTranslation` in order for the Typescript to work properly with multiple namespaces. You can see that this is how they do it in their example here: 
https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple-multi-namespaces/src

So it seems that this is how they designed it to work. Personally, I would use the `const { i18n: { t } } = useTranslation()` method instead since it's cleaner. 

We've left this issue open to ensure that our implementation in our i18next example is not at fault here. Given that the i18next official example says to put the namespaces as an argument to `useTranslation`, it sounds like there is not an issue with our example.

We're going to close this issue now. But happy to continue helping out in this thread if you need more support.

**Closed by i18nexus** 2024-03-13 17:28 UTC

**Comment by geminiyellow** [comment] 2024-05-01 02:47
hi sir, can you give a multi namespace demo? the i18next-sample use multiple namespace not working.
