### ISSUE TITLE
TranslationsProvider changes rendering to full client side for all the page removing all html from body (very bad for seo)

### ISSUE THREAD

**Issue by andretti1977** [i18nexus/next-i18n-router#31] opened 2023-11-08 13:40 UTC
If you run i18next-example nextjs application and for example check the rendered page source code at /about, you'll see that the html source code in the body tag is something like this:
```
...
...
</head>
  <body class="__className_e66fe9">
    <script src="/_next/static/chunks/webpack.js?v=1699439842254" async=""></script>
    <script>
      (self.__next_f = self.__next_f || []).push([0]);
      self.__next_f.push([2, null])
    </script>
    <script>
      self.__next_f.push([1, "0:\"$L1\"\n"])
    </script>
    <script>
      self.__next_f.push([1, "2:HL[\"/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n3:HL[\"/_next/static/css/app/[locale]
...
...
```
This code is completely missing html tags and it's only javascript code. Generated code should be different when server side rendered, it should be in this form (you can obtain this code if you remove TranslationsProvider from `app/\[locale\]/about/page.tsx`, you will lose client side translations but will be able to see an example of how server side code should be rendered which is a mix of html tags and js functions):
```
...
...
</head>
  <body class="__className_e66fe9">
    <main class="page_main__d9_kd">
      <h1>Welcome to my About page</h1>
      <a href="/">back</a>
      <select>
        <option value="en">English</option>
        <option value="de">Deutsch</option>
        <option value="ja">日本語</option>
      </select>
    </main>
    <script src="/_next/static/chunks/webpack.js?v=1699450478193" async=""></script>
    <script>
      (self.__next_f = self.__next_f || []).push([0]);
      self.__next_f.push([2, null])
    </script>
...
...
```

Can you provide a solution or a hint at what and why is it happening?

Thanks in advance

**Comment by i18nexus** [comment] 2023-11-08 17:58
This is interesting. Thank you for letting us know. We'll take a look at this and get back soon.

**Comment by andretti1977** [comment] 2023-11-08 18:12
Thank you, to be honest, i'm desperate! I'm trying to implement a new project for a customer using NextJs app router but it's a continuous source of problems and even internationalization is now delivering problems. Internationalization should be  something incredibly easy since you should be able to identify the locale you are using and provide a simple map with key-values translated...but TranslationsProvider now deletes all html...

**Comment by i18nexus** [comment] 2023-11-08 18:38
I understand, we're taking a look now. It appears our react-intl example renders correctly if you are not partial to using i18next. In the meantime, we're currently debugging the i18next example.

**Comment by i18nexus** [comment] 2023-11-08 18:52
Quick update here:

The issue seems to stem from the async nature of creating the i18n instance in TranslationsProvider. The reason that HTML is not rendered is because of this:

```
  if (!instance) {
    return null;
  }
 ```
 
 If you replace `null` with some HTML element, you will see that the element is rendered in the response. So the SSG is currently working, but the page just has no content on first render.
 
 That being said, we're working on an update to the example to remove the async nature of the component. Will report back soon.

**Comment by andretti1977** [comment] 2023-11-08 19:03
yes i discovered the problem was with the `return null` but if you try to return something (it would make sense to return `<>{children}</>`) then you have a "flickering" effect since the page is immediately rendered as server side but the "client side" labels aren't translated and defaults appears. After a while (when the useEffect in TranslationsProvider is triggered) the labels get rendered client side but at that point you see the label rewritten.

I'd like to adopt i18next but would use react-intl even if it seems that is a bit different in code structure and i didn't understand if it works both server and client side.

**Comment by i18nexus** [comment] 2023-11-09 18:29
We have a come up with a solution.

We're still undergoing testing, but this seems to work great. We've set it up to work more like our react-intl example so that the messages loaded in the server i18next instance are passed as props to the client i18next instance. This should not only make performance better but also solves your issue.

The apparent downside of this solution is that a new i18next instance is generated per page instead of having a global client instance that is created one time like before. But this should not be an issue because now that we're loading the resources directly from props, the instance does not have to import translations. This makes instance creation quick and cheap.

I will close this issue once we officially update our example.

i18n.ts
```
import { Resource, createInstance, i18n } from 'i18next';
import { initReactI18next } from 'react-i18next/initReactI18next';
import resourcesToBackend from 'i18next-resources-to-backend';
import i18nConfig from '@/i18nConfig';

export default async function initTranslations(
  locale: string,
  namespaces: string[],
  i18nInstance?: i18n,
  resources?: Resource
) {
  i18nInstance = i18nInstance || createInstance();

  i18nInstance.use(initReactI18next);

  if (!resources) {
    i18nInstance.use(
      resourcesToBackend(
        (language: string, namespace: string) =>
          import(`@/locales/${language}/${namespace}.json`)
      )
    );
  }

  await i18nInstance.init({
    lng: locale,
    resources,
    fallbackLng: i18nConfig.defaultLocale,
    supportedLngs: i18nConfig.locales,
    defaultNS: namespaces[0],
    fallbackNS: namespaces[0],
    ns: namespaces,
    preload: resources ? [] : i18nConfig.locales,
    debug: true
  });

  return {
    i18n: i18nInstance,
    resources: i18nInstance.services.resourceStore.data,
    t: i18nInstance.t
  };
}
```

TranslationsProvider.ts
```
'use client';

import { I18nextProvider } from 'react-i18next';
import { ReactNode } from 'react';
import initTranslations from '@/app/i18n';
import { Resource, createInstance } from 'i18next';

export default function TranslationsProvider({
  children,
  locale,
  namespaces,
  resources
}: {
  children: ReactNode;
  locale: string;
  namespaces: string[];
  resources: Resource;
}) {
  const i18n = createInstance();

  initTranslations(locale, namespaces, i18n, resources);

  return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>;
}
```

page.tsx
```
import ExampleClientComponent from '@/components/ExampleClientComponent';
import styles from './page.module.css';
import LanguageChanger from '@/components/LanguageChanger';
import Link from 'next/link';
import initTranslations from '../i18n';
import TranslationsProvider from '@/components/TranslationsProvider';

const i18nNamespaces = ['home'];

async function Home({ params: { locale } }: { params: { locale: string } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}>
      <main className={styles.main}>
        <h1>{t('header')}</h1>
        <ExampleClientComponent />
        <Link href="/about">{t('page2')}</Link>
        <LanguageChanger />
      </main>
    </TranslationsProvider>
  );
}

export default Home;
```

**Comment by andretti1977** [comment] 2023-11-10 13:43
Thank you very much, your code works perfectly! Now i have both client and server side localizations as expected with html seo compliant!

**Comment by A-AllaaEddine** [comment] 2023-11-21 11:14
I did try your solution in my project and I can confirm it works.

**Comment by i18nexus** [comment] 2023-11-22 00:22
The i18next example in the repo has now been updated with the above code. Thanks everyone for the feedback!

**Closed by i18nexus** 2023-11-22 00:22 UTC
