### ISSUE TITLE
Routing with a default locale and nesting greater than one does not function.

### ISSUE THREAD

**Issue by oskolsky** [i18nexus/next-i18n-router#23] opened 2023-10-01 23:42 UTC
Hello, thank you for the work you do. I have encountered the following issue:

I have the following nested directory structure in my app:

<img width="206" alt="Screenshot 2023-10-02 at 02 40 08" src="https://github.com/i18nexus/next-i18n-router/assets/1423686/a3a9217a-68ac-49a9-a6fe-61209bfa464c">

My config:

```
const i18nConfig: Config = {
    locales: ['en', 'lt'],
    defaultLocale: 'en',
    prefixDefault: false,
    routingStrategy: 'dynamicSegment',
}
```

Problem:

Url http://localhost:3000/map - working, and I have en locale
Url http://localhost:3000/places/70 - not working, and I have default Nextjs error page (404)

I noticed that issues with the default locale start when the path nesting is more than 2.
If change the value of prefixDefault to true, everything works as it should.

**Comment by i18nexus** [comment] 2023-10-02 18:07
Thanks for the report! 
Not sure how this was missed in our tests, but it is now fixed in v4.1.0 🙂

**Closed by i18nexus** 2023-10-02 18:07 UTC

**Comment by oskolsky** [comment] 2023-10-02 19:12
Excellent thank you!

**Comment by jthill57** [comment] 2023-11-09 20:19
It seems like this bug is reintroduced since v5.0.0? I have a similar folder structure and routing on the defaultLocale with prefixDefault set to false still results in 404 not found.

**Comment by i18nexus** [comment] 2023-11-09 21:01
Hi @jthill57. That's strange. I'm attempting to reproduce this on v5.0 but I cannot. Can you ensure you're on the latest version? If you are, can you try to reproduce this on one of our examples?

**Comment by jthill57** [comment] 2023-11-09 21:09
@i18nexus my bad... after investigation it was a bad copy paste on my end with the middleware.js (was missing an extra \ in the matcher).

**Comment by i18nexus** [comment] 2023-11-09 21:13
@jthill57 Cool, glad you found it 👍
