### ISSUE TITLE
Error: Invariant: headers() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by weeny-V** [i18nexus/next-i18n-router#16] opened 2023-09-10 14:56 UTC
When I'm trying to set 'export const runtime = "edge"' and after adding this line all i18n is broken
![image](https://github.com/i18nexus/next-i18n-router/assets/48623554/efe2715d-e31f-4f2a-b35b-30bed8fdc68a)

**Comment by i18nexus** [comment] 2023-09-12 04:49
That interesting. Can you tell me what version of next you’re using?

**Comment by weeny-V** [comment] 2023-09-12 07:28
version of next is 13.4.19

**Comment by i18nexus** [comment] 2023-09-13 19:20
Unfortunately we can't reproduce this. Are you able to provide a minimal reproducible example?

**Comment by weeny-V** [comment] 2023-09-14 11:53
yeah, sure
First screenshot with all your settings and work correctly:
![267887791-433b20ed-b1fc-4e3b-bf56-0e52f3e2e524](https://github.com/i18nexus/next-i18n-router/assets/48623554/e02f4597-79cd-4389-ba73-fce69a8d495e)
The second screenshot with runtime value does not work:
![267888185-4603bbac-90e5-4be5-a429-3b8a4a1a3a5e](https://github.com/i18nexus/next-i18n-router/assets/48623554/2a5bcc89-b87a-41a8-b9ea-16871e9b2d00)
![267888555-a1710e56-bea2-4b27-808f-39ed3dce0204](https://github.com/i18nexus/next-i18n-router/assets/48623554/c38057f1-183a-4bf1-873f-2572fbd684b3)

**Comment by i18nexus** [comment] 2023-09-14 19:56
After some research, there is an open issue on the Next repo about this: https://github.com/vercel/next.js/issues/52176

There appears to be a bug when using `headers` in the edge runtime.

Unfortunately there's not much we can do until this is resolved in Next. If you're using supabase, this seems to be a possible workaround: https://github.com/vercel/next.js/issues/45371#issuecomment-1655408690

**Comment by i18nexus** [comment] 2023-09-17 19:48
We are going to close this issue since it’s a bug in Next and not with next-i18n-router.

**Closed by i18nexus** 2023-09-17 19:48 UTC
