### ISSUE TITLE
How do you render the `not-found` page?

### ISSUE THREAD

**Issue by HamedBahram** [i18nexus/next-i18n-router#36] opened 2023-11-21 17:35 UTC
I cannot find a way to implement the `not-found` page with this folder structure in the App router.

**Comment by i18nexus** [comment] 2023-11-22 00:07
This is a duplicate of #32. But I'll elaborate and show a workaround here.

Essentially the issue is that automatic redirects to `not-found` do not work inside of a dynamic segment like [locale]. So you need to use a catch-all that calls `notFound()`. 

Another problem is that inside of your `not-found` page you will not have access to page params. So you cannot access the locale from page params. You can instead use the locale from the header `x-i18n-router-locale` if you want to localize this not-found page.

These are not issues specific to next-i18n-router. They are quirks in Next.js app router.

You will need:
- Catch all component: `[...not_found]/page.tsx`
- Not found page: `not-found.tsx`

**[...not_found]/page.tsx**:
```
import { notFound } from 'next/navigation';

export default function NotFoundCatchAll() {
  notFound();
}
```

**not-found.tsx**:
```
import { headers } from 'next/headers';

export default async function NotFound() {
  const headersList = headers();
  const locale = headersList.get('x-i18n-router-locale') || 'en';
  
  ...
}
```

**Closed by i18nexus** 2023-11-22 00:07 UTC

**Comment by Zerebokep** [comment] 2023-11-23 10:46
@i18nexus x-i18n-router-locale always seems to be null, is there any requirement for it? I'm using 5.0.2.

**Comment by i18nexus** [comment] 2023-11-29 22:18
@Zerebokep Sorry, just saw this. The most common reason this occurs is that the middleware is not running. If you are using the `/src` directory, make sure your `middleware.js` file is inside of the `/src` directory. If not, please check your config matcher in your middleware. It should look like this:


```
// only applies this middleware to files in the app directory
export const config = {
  matcher: '/((?!api|static|.*\\..*|_next).*)'
};
```

If neither of these solve your problem, please paste your `middleware.js` file here as well as your config file.

**Comment by Zerebokep** [comment] 2023-11-30 14:43
No worries.

this is my middleware.ts which is inside the src/app/ folder

```
export async function middleware(request: NextRequest) {
  return i18nRouter(request, i18nConfig)
}

export const config = {
  matcher: '/((?!api|static|.*\\..*|_next).*)',
}
```

btw. I'm still using the "old" useEffect method of the TranslationProvider, maybe this has something to do with it?

**Comment by i18nexus** [comment] 2023-11-30 17:27
@Zerebokep  Ah, your problem is that your middleware needs to be outside of the `/app` folder. It should be directly inside of `/src`.

Side note, I highly recommend switching to the new version of the i18next example. It's quite easy to change.

**Comment by Zerebokep** [comment] 2023-11-30 19:35
@i18nexus oh my bad, it is actually there, I misdescribed it in my earlier post.

**Comment by i18nexus** [comment] 2023-11-30 22:47
@Zerebokep Can you put a console log in your middleware function to make sure its being called?

**Comment by yannjor** [comment] 2024-10-21 08:59
Hey @i18nexus ! Your suggested solution works, but it broke my SSG routes. Any ideas why this might be?

**Comment by i18nexus** [comment] 2024-10-21 17:36
@yannjor Can you elaborate on what you mean by it breaking your SSG routes? Any error messages?

**Comment by yannjor** [comment] 2024-10-21 19:41
@i18nexus of course, sorry my original message was so clear.

This is how I'm trying to render the not-found page. `src/app/[locale]/not-found`:

```tsx
import React from 'react';
import styles from './NotFoundPage.module.css';
import Hero from '@/components/Hero';
import { PrismicRichText } from '@prismicio/react';
import typography from '@/styles/typography.module.css';
import i18nConfig from '@/i18nConfig';
import { fetchSingleStaticPage } from '@/model/staticPage/fetch';
import { headers } from 'next/headers';

export default async function NotFound() {
  const headersList = headers();
  const locale =
    headersList.get('x-next-i18n-router-locale') || i18nConfig.defaultLocale;
  const page = await fetchSingleStaticPage('not-found', locale);

  return (
    <main>
      <Hero doc={page} />
      <article className={styles.notFound}>
        <p className={typography.body2}>
          <PrismicRichText field={page.description} />
        </p>
      </article>
    </main>
  );
}
```

and `src/app/[locale]/[...not-found]/page.tsx`:

```tsx
import { notFound } from 'next/navigation';

export default function NotFoundCatchAll() {
  notFound();
}
```

When I build the app, everything looks good, no error messages, except that when I look in the built `.next` directory, none of my statically generated routes have been built. The weird thing is, when I remove the `next/headers` code, it builds correctly. But then I don't get my localized 404 pages 🫠

**Comment by i18nexus** [comment] 2024-10-22 16:48
Interesting, we'll look into this. Are you using `generateStaticParams` for the locales?

**Comment by yannjor** [comment] 2024-10-22 18:07
> Interesting, we'll look into this. Are you using `generateStaticParams` for the locales?

Yes

**Comment by yannjor** [comment] 2024-10-25 06:35
@i18nexus It says in the [Next.js docs](https://nextjs.org/docs/app/api-reference/functions/headers) that:

 "`headers` is a [Dynamic API](https://nextjs.org/docs/app/building-your-application/rendering/server-components#server-rendering-strategies#dynamic-apis) whose returned values cannot be known ahead of time. Using it in will opt a route into [dynamic rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering)."

 So perhaps this is the reason.

**Comment by i18nexus** [comment] 2024-10-25 06:46
Sorry on the delay digging into this. But in the meantime, I think [this comment](https://github.com/vercel/next.js/discussions/43179#discussioncomment-10647599) may be the best solution. But again, we will look further into this by next week and report if there's a better solution. [This thread](https://github.com/vercel/next.js/discussions/43179#discussioncomment-10647599) is basically a bunch of people with the same problem.

**Comment by yannjor** [comment] 2024-11-11 08:13
@i18nexus I found this workaround that works: https://github.com/vercel/next.js/discussions/43179#discussioncomment-11192893
